# Generated by Django 2.0.3 on 2018-05-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180519_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cupons.Cupon'),
        ),
    ]
